apiVersion: apps/v1

kind: Deployment
metadata:
  name: bull-exporter
  labels:
    app: bull
    role: exporter

spec:
  selector:
    matchLabels:
      app: bull
      role: exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: bull
        role: exporter

    spec:
      automountServiceAccountToken: false
      containers:
        - name: bull-exporter
          image: uphabit/bull_exporter:latest
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 200m
              memory: 512M

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          env:
            - name: EXPORTER_AUTODISCOVER	
              value: "true"

            #- name: EXPORTER_REDIS_URL
              #value: redis cluster url

          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: 5959
